### ISSUE TITLE
Trying to add theme to project [undefined isIphoneX]

### ISSUE THREAD

**Issue by dacastro4** [GeekyAnts/KitchenSink-Vue-Native#13]
I'm trying to add the theme using `nb-style-provider` but I haven't being able to make it work.

```
<nb-style-provider :style="getTheme(platform)">
...
```

I haven't changed anything I just ran ` node node_modules/native-base/ejectTheme.js` and tried to import it

![Simulator Screen Shot - iPhone XR - 2019-03-08 at 23 15 07](https://user-images.githubusercontent.com/7808930/54066074-07332d00-41f8-11e9-8c3e-e28447492b50.png)

**Comment by melvinchng** [comment]
I am also facing the same issue. Have you managed to fix it?

**Comment by melvinchng** [comment]
I followed [these instructions ](https://github.com/GeekyAnts/NativeBase/issues/2067)and it fixes the issue.

**Comment by RishabhKarnad** [comment]
@dacastro4 The solution provided by @melvinchng is the recommended solution for now. Closing this issue.
