### ISSUE TITLE
removing class="container" caused bug

### ISSUE THREAD

**Issue by vortechron** [GeekyAnts/KitchenSink-Vue-Native#14]
from here `KitchenSink-Vue-Native/src/boot/setup.vue`

Plot 🗡 
i try to remove the class, but when i run the app, i got white screen, when i add the class back, everything back to normal. hm

**Comment by RishabhKarnad** [comment]
The container class ensures the text is centered on the screen. Removing it makes the text go to the top of the screen, so it might be hidden behind your status bar.
