### ISSUE TITLE
Unable to resolve @expo/vector-icons/AntDesign

### ISSUE THREAD

**Issue by pratik007kumar** [GeekyAnts/KitchenSink-Vue-Native#15]
I am not able to run app in it showing following issue
```
Unable to resolve @expo/vector-icons/AntDesign" from ".//node_modules/native-base/dist/src/basic/IconNB.js"
```
![Screenshot from 2019-04-10 15-56-33](https://user-images.githubusercontent.com/9718704/55871913-58449100-5ba9-11e9-9d4a-7b32d7e4d0ce.png)

**Comment by neeraj-singh47** [comment]
@pratik007kumar https://github.com/GeekyAnts/NativeBase/issues/2506#issuecomment-466798735
