### ISSUE TITLE
Error on expo

### ISSUE THREAD

**Issue by adeyinkakoya** [GeekyAnts/KitchenSink-Vue-Native#18]
I need help guys. I have not been able to get past this error after cloning your App.
![Screenshot_20190913-221728](https://user-images.githubusercontent.com/41973776/64895562-d9321800-d674-11e9-9d59-7a849d074e41.png)

**Comment by RishabhKarnad** [comment]
Please try again with the latest version of expo-cli and the updated code from master. Please reopen the issue if this persists
