### ISSUE TITLE
Cannot render app

### ISSUE THREAD

**Issue by ghost** [GeekyAnts/KitchenSink-Vue-Native#2]
Using the exact repo I can't finish the build, using Expo and here's the screen with error.

![img_1344](https://user-images.githubusercontent.com/29777438/41402916-d129d53a-6fc3-11e8-8724-46512567d4d2.PNG)

**Comment by aaronksaunders** [comment]
see exact same issue - this ONLY works if I use a specific version of native-base     
```
"native-base": "https://github.com/GeekyAnts/NativeBase#v2.4.2-2",
```

also noticed this PR... **added vue-native-base component and its corresponding vue-plugin #1791** https://github.com/GeekyAnts/NativeBase/pull/1791

**Comment by gauravprwl14** [comment]
@rafal-olszewski we have update the native-base package to 2.6.0, which has the support for the Vue-Native.

You can run 
```
npm install native-base
```
and try running the app again, after installing the native-base package.

**Comment by nuno** [comment]
@aaronksaunders thanks, that version works for me, otherwise won't work here. 
Every time I tap on each menu i got:

`TypeError: undefined is not an object (evaluating 'this.props.style[1].height') .... `   X 5  or 6 times

**Comment by aaronksaunders** [comment]
So the fix with the latest version is not working?

**Comment by nuno** [comment]
I don't think so.

EDITED: 
I had to change:

`"native-base": "2.6.0"`
to
` "native-base": "https://github.com/GeekyAnts/NativeBase#v2.4.2-2",`

**Comment by nuno** [comment]
@aaronksaunders @gauravprwl14 

"native-base": "2.6.0"
Every time I tap on each menu:

![screen shot 2018-06-24 at 17 06 22](https://user-images.githubusercontent.com/38348/41820925-1ff2e304-77d1-11e8-8d2b-94dd5eb742c7.png)
