### ISSUE TITLE
'expo' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Manishkini** [GeekyAnts/KitchenSink-Vue-Native#24]
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kitchenSink-vue-native@0.2.0 start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kitchenSink-vue-native@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manish Kini\AppData\Roaming\npm-cache\_logs\2020-01-12T05_15_25_455Z-debug.log

**Comment by RishabhKarnad** [comment]
expo-cli needs to be installed

```
npm i expo-cli -g
```
