### ISSUE TITLE
project is not run

### ISSUE THREAD

**Issue by maxisteve** [GeekyAnts/KitchenSink-Vue-Native#26]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kitchenSink-vue-native@0.2.0 start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kitchenSink-vue-native@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-06-29T16_39_08_330Z-debug.log
**here i attach the log file please suggest me what is the issue
[2020-06-18T08_54_51_095Z-debug.log](https://github.com/GeekyAnts/KitchenSink-Vue-Native/files/4846917/2020-06-18T08_54_51_095Z-debug.log)
**

**Comment by welldy33** [comment]
I Found Same Issue

**Comment by AndresV22** [comment]
I used this guide [https://medium.com/@sanidhyaagrawal08/react-native-error-invalid-regular-expression-7ebbcd7d2788](https://medium.com/@sanidhyaagrawal08/react-native-error-invalid-regular-expression-7ebbcd7d2788) but it is still not running, now it throw another error:

null is not an object (evaluatin '_NativeAppearance.NativeAppearance.initialPreferences')

**Comment by RishabhKarnad** [comment]
Should be resolved now after the upgrade to Expo SDK 40
