### ISSUE TITLE
Update Expo SDK

### ISSUE THREAD

**Issue by shaqaruden** [GeekyAnts/KitchenSink-Vue-Native#27]
Project needs to be updated to support expo sdk 36 or higher. I attempted this myself by running `expo update` (updating to v39) though this completed the project still does not run

**Comment by shaqaruden** [comment]
$ expo start --android
Starting project at C:\Users\chad_gregory\Apps\VueNative\KitchenSink-Vue-Native
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
error: unknown option `--assetExts'

Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\@expo\xdl@58.0.19\src\Project.ts:1596:16)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by RishabhKarnad** [comment]
Upgraded to Expo SDK 40
