### ISSUE TITLE
 Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `StyleProvider`, expected `object`.

### ISSUE THREAD

**Issue by kranopodem** [GeekyAnts/KitchenSink-Vue-Native#6]
Hello. Why are StyleProvider not taking the theme, and throwing warning "Failed prop type: Invalid prop style of type array supplied to StyleProvider, expected object."

`<template>`
`<nb-style-provider v-bind:style="getTheme(material)">`
`<nb-container>`
`<nb-text>Contact</nb-text>`
`</nb-container>`
`</nb-style-provider>`
`</template>`
`<script>`
`import Vue from "vue-native-core";`
`import {VueNativeBase} from "native-base";`
`import getTheme from './native-base-theme/components';`
`import material from './native-base-theme/variables/material';`

`Vue.use(VueNativeBase);`
`export default {`
  `data: function() {`
   ` return {`
    `  getTheme: getTheme,`
     ` material: material,`
    `};`
  `},`
`};`
`</script>`

**Comment by neeraj-singh47** [comment]
You'll have to create a separate react component to use theme for now and then import that theme as root component within your vue file.

**Comment by arihantdaga** [comment]
@neeraj-singh47  Can you provide any example for that ?

**Comment by kranopodem** [comment]
@arihantdaga Try [this one](https://github.com/GeekyAnts/NativeBase/issues/2067#issuecomment-400925259)

**Comment by arihantdaga** [comment]
@kranopodem  Thank you. Very helpful.
